In [3]:
%conda install PyVCF

Collecting package metadata (current_repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/osx-64::gym-all==0.21.0=py39h6e9494a_2
  - conda-forge/osx-64::gym-toy_text==0.21.0=py39h6e9494a_2
done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /Users/fionachow/opt/anaconda3/envs/rl

  added / updated specs:
    - pyvcf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.2.2   |       h8857fd0_0         152 KB  conda-forge
    openssl-3.2.1              |       hd75f5a5_1         2.4 MB  conda-forge
    pyvcf-0.6.8                |py39h6e9494a_1003          69 KB  conda-forge
    scipy-1.12.0               |   py39ha516a68_0        21.9 MB
    ------------------------------------------------------------
                                           Total:        24.5 MB

The following NEW packages will be INSTALLED:

  pyvcf              conda-forge/osx-64::pyvcf-0.6.8-py39h6e9494a_1003 None
  scipy              pkgs/main/osx-64::scipy-1.12.0-py39ha516a68_0 None

The following packages will be UPDATED:

  ca-certificates                     2023.11.17-h8857fd0_0 --> 2024.2.2-h8857fd0_0 None
  openssl                                  3.2.0-hd75f5a5_1 --> 3.2.1-hd75f5a5_1 None



Downloading and Extracting Packages
scipy-1.12.0         | 21.9 MB   | ##################################### | 100%
ca-certificates-2024 | 152 KB    | ##################################### | 100%
pyvcf-0.6.8          | 69 KB     | ##################################### | 100%
openssl-3.2.1        | 2.4 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [4]:
import io
import os
import pandas as pd
import re
import vcf

In [18]:
def read_vcf(path):
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    match = re.search(r'AF=([\d\.]+)', info)
    return match.group(1) if match else None

def filter_vcf(vcf_file):
    vcf_reader = vcf.Reader(open(vcf_file, 'r'))

    for record in vcf_reader:
        if 'AF' in record.INFO and record.INFO['AF'] > 0.5:
            print(record)

In [6]:
df = read_vcf('/Users/fionachow/Documents/ERR3240115_rDNA.vcf') #vcf file from original variant calling of 1 individual

df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1"
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1"
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10"
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10"
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE..."
...,...,...,...,...,...,...,...,...
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND..."
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND..."
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL..."
377,Human,13280,.,G,C,13572,PASS,"DP=1017;AF=1.000000;SB=0;DP4=0,0,2,1015"
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H..."

In [7]:
#extracting AF into a seperate column
df['AF'] = df['INFO'].apply(extract_af)

df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1",1.000000
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1",1.000000
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10",0.996952
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10",0.999624
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
...,...,...,...,...,...,...,...,...,...
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND...",0.944088
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL...",0.909971
377,Human,13280,.,G,C,13572,PASS,"DP=1017;AF=1.000000;SB=0;DP4=0,0,2,1015",1.000000
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H...",0.913212

In [14]:
type(df.loc[2, 'AF']) #string type

str

In [16]:
df['AF'] = df['AF'].astype(float) #converting format to float

type(df.loc[2, 'AF'])

numpy.float64

In [18]:
filtered_df = df[df['AF'] > 0.5] #filtering for AF threshold >0.5; extracting majority alleles at each position from variant calling

filtered_df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1",1.000000
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1",1.000000
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10",0.996952
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10",0.999624
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
...,...,...,...,...,...,...,...,...,...
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND...",0.944088
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL...",0.909971
377,Human,13280,.,G,C,13572,PASS,"DP=1017;AF=1.000000;SB=0;DP4=0,0,2,1015",1.000000
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H...",0.913212

In [19]:
#alt way to read vcf files filtered for variant positions
filter_vcf('/Users/fionachow/Documents/ERR3240115_rDNA.vcf') #similar outputs to the pandas filter

Record(CHROM=Human, POS=31, REF=T, ALT=[C])
Record(CHROM=Human, POS=32, REF=C, ALT=[T])
Record(CHROM=Human, POS=73, REF=C, ALT=[A])
Record(CHROM=Human, POS=74, REF=A, ALT=[C])
Record(CHROM=Human, POS=80, REF=A, ALT=[AC])
Record(CHROM=Human, POS=103, REF=GC, ALT=[G])
Record(CHROM=Human, POS=121, REF=C, ALT=[G])
Record(CHROM=Human, POS=237, REF=G, ALT=[GC])
Record(CHROM=Human, POS=270, REF=C, ALT=[CG])
Record(CHROM=Human, POS=275, REF=C, ALT=[CG])
Record(CHROM=Human, POS=284, REF=A, ALT=[AC])
Record(CHROM=Human, POS=363, REF=G, ALT=[GT])
Record(CHROM=Human, POS=386, REF=T, ALT=[TGGCC])
Record(CHROM=Human, POS=419, REF=C, ALT=[CGT])
Record(CHROM=Human, POS=517, REF=G, ALT=[GC])
Record(CHROM=Human, POS=522, REF=C, ALT=[CG])
Record(CHROM=Human, POS=524, REF=C, ALT=[G])
Record(CHROM=Human, POS=537, REF=TG, ALT=[T])
Record(CHROM=Human, POS=560, REF=C, ALT=[G])
Record(CHROM=Human, POS=561, REF=G, ALT=[GT])
Record(CHROM=Human, POS=623, REF=C, ALT=[CT])
Record(CHROM=Human, POS=626, REF=T, ALT=[G])
Record(CHROM=Human, POS=673, REF=G, ALT=[C])
Record(CHROM=Human, POS=674, REF=C, ALT=[G])
Record(CHROM=Human, POS=763, REF=CGG, ALT=[C])
Record(CHROM=Human, POS=1671, REF=GCTCCC, ALT=[G])
Record(CHROM=Human, POS=1677, REF=A, ALT=[T])
Record(CHROM=Human, POS=1749, REF=C, ALT=[T])
Record(CHROM=Human, POS=1756, REF=GT, ALT=[G])
Record(CHROM=Human, POS=2392, REF=G, ALT=[C])
Record(CHROM=Human, POS=2484, REF=G, ALT=[A])
Record(CHROM=Human, POS=2486, REF=TGCG, ALT=[T])
Record(CHROM=Human, POS=2553, REF=C, ALT=[G])
Record(CHROM=Human, POS=3002, REF=T, ALT=[G])
Record(CHROM=Human, POS=3004, REF=C, ALT=[T])
Record(CHROM=Human, POS=3006, REF=T, ALT=[C])
Record(CHROM=Human, POS=3090, REF=G, ALT=[C])
Record(CHROM=Human, POS=3152, REF=GC, ALT=[G])
Record(CHROM=Human, POS=3411, REF=GC, ALT=[G])
Record(CHROM=Human, POS=3635, REF=G, ALT=[C])
Record(CHROM=Human, POS=5293, REF=AG, ALT=[A])
Record(CHROM=Human, POS=5303, REF=CG, ALT=[C])
Record(CHROM=Human, POS=5680, REF=C, ALT=[CG])
Record(CHROM=Human, POS=5692, REF=C, ALT=[CG])
Record(CHROM=Human, POS=5839, REF=A, ALT=[G])
Record(CHROM=Human, POS=5891, REF=TG, ALT=[T])
Record(CHROM=Human, POS=6534, REF=TGGGC, ALT=[T])
Record(CHROM=Human, POS=6791, REF=G, ALT=[GC])
Record(CHROM=Human, POS=7025, REF=G, ALT=[GCCCGC])
Record(CHROM=Human, POS=7321, REF=TC, ALT=[T])
Record(CHROM=Human, POS=7362, REF=CG, ALT=[C])
Record(CHROM=Human, POS=7369, REF=TC, ALT=[T])
Record(CHROM=Human, POS=7512, REF=C, ALT=[CCGGCCG])
Record(CHROM=Human, POS=7661, REF=C, ALT=[G])
Record(CHROM=Human, POS=7717, REF=C, ALT=[G])
Record(CHROM=Human, POS=7719, REF=C, ALT=[T])
Record(CHROM=Human, POS=7994, REF=A, ALT=[G])
Record(CHROM=Human, POS=8065, REF=C, ALT=[CGCG])
Record(CHROM=Human, POS=8178, REF=G, ALT=[GCCC])
Record(CHROM=Human, POS=8187, REF=C, ALT=[CCGG])
Record(CHROM=Human, POS=8688, REF=C, ALT=[CCCGT])
Record(CHROM=Human, POS=8804, REF=G, ALT=[C])
Record(CHROM=Human, POS=10881, REF=C, ALT=[CCG])
Record(CHROM=Human, POS=10931, REF=A, ALT=[AC])
Record(CHROM=Human, POS=10959, REF=A, ALT=[G])
Record(CHROM=Human, POS=11033, REF=C, ALT=[CG])
Record(CHROM=Human, POS=11069, REF=GC, ALT=[G])
Record(CHROM=Human, POS=11101, REF=A, ALT=[AC])
Record(CHROM=Human, POS=11104, REF=T, ALT=[TC])
Record(CHROM=Human, POS=11118, REF=GC, ALT=[G])
Record(CHROM=Human, POS=11126, REF=G, ALT=[C])
Record(CHROM=Human, POS=11149, REF=C, ALT=[G])
Record(CHROM=Human, POS=11150, REF=G, ALT=[C])
Record(CHROM=Human, POS=11268, REF=CG, ALT=[C])
Record(CHROM=Human, POS=11293, REF=C, ALT=[CG])
Record(CHROM=Human, POS=11485, REF=C, ALT=[CG])
Record(CHROM=Human, POS=11936, REF=G, ALT=[GC])
Record(CHROM=Human, POS=12011, REF=G, ALT=[GC])
Record(CHROM=Human, POS=12046, REF=G, ALT=[GGCCGCGC])
Record(CHROM=Human, POS=12047, REF=C, ALT=[G])
Record(CHROM=Human, POS=12388, REF=G, ALT=[A])
Record(CHROM=Human, POS=12624, REF=C, ALT=[CG])
Record(CHROM=Human, POS=12722, REF=C, ALT=[CGCG])
Record(CHROM=Human, POS=12998, REF=C, ALT=[CG])
Record(CHROM=Human, POS=13011, REF=T, ALT=[C])
Record(CHROM=Human, POS=13068, REF=C, ALT=[CG])
Record(CHROM=Human, POS=13079, REF=T, ALT=[TG])
Record(CHROM=Human, POS=13084, REF=T, ALT=[G])
Record(CHROM=Human, POS=13113, REF=C, ALT=[CG])
Record(CHROM=Human, POS=13150, REF=A, ALT=[AC])
Record(CHROM=Human, POS=13219, REF=C, ALT=[CG])
Record(CHROM=Human, POS=13235, REF=GC, ALT=[G])
Record(CHROM=Human, POS=13278, REF=G, ALT=[GGC])
Record(CHROM=Human, POS=13280, REF=G, ALT=[C])
Record(CHROM=Human, POS=13288, REF=G, ALT=[GC])

In [17]:
mpileup_file_path = '/Users/fionachow/Documents/ERR3240115_rDNA.mpileup' #extracting reference alleles for all Positions

mpileup_df = pd.read_csv(mpileup_file_path, sep='\t', header=None, usecols=[0, 1, 2], names=['CHROM', 'POS', 'REF'])

mpileup_df.head(32)

    CHROM  POS REF
0   Human    1   G
1   Human    2   C
2   Human    3   T
3   Human    4   G
4   Human    5   A
5   Human    6   C
6   Human    7   A
7   Human    8   C
8   Human    9   G
9   Human   10   C
10  Human   11   T
11  Human   12   G
12  Human   13   T
13  Human   14   C
14  Human   15   C
15  Human   16   T
16  Human   17   C
17  Human   18   T
18  Human   19   G
19  Human   20   G
20  Human   21   C
21  Human   22   G
22  Human   23   A
23  Human   24   C
24  Human   25   C
25  Human   26   T
26  Human   27   G
27  Human   28   T
28  Human   29   C
29  Human   30   G
30  Human   31   T
31  Human   32   C