In [1]:
#%conda install PyVCF

In [2]:
import io
import os
import pandas as pd
import re
import vcf

In [3]:
def read_vcf(path):
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    match = re.search(r'AF=([\d\.]+)', info)
    return match.group(1) if match else None

def filter_vcf(vcf_file):
    vcf_reader = vcf.Reader(open(vcf_file, 'r'))

    for record in vcf_reader:
        if 'AF' in record.INFO and record.INFO['AF'] > 0.5:
            print(record)

def fasta_to_all_chars_dataframe(filepath):
    """ 
    Parses a FASTA file and returns a DataFrame with all characters enumerated
    """
    with open(filepath, 'r') as file:
        position = 1  
        data = []  
        for line in file:
            for char in line:
                if char == '\n':
                    data.append((position, 'line_break', '\\n'))
                else:
                    data.append((position, 'sequence' if char != '>' else 'header', char))
                position += 1

    return pd.DataFrame(data, columns=['POS', 'Type', 'REF'])

def find_deletions(row):
    """ 
    Determines deletions
    """
    pos = row['POS']
    ref = row['REF']
    alt = row['ALT']
    deletions = []
    start_deletion = pos + len(alt)
    # Subtract the ALT length from REF to determine the deletions
    extra_bases = ref[len(alt):]
    for i, base in enumerate(extra_bases, start=start_deletion):
        deletions.append((i, base))
        
    return deletions

def replace_ref(row):
    if  row['REF_x'] == row['Base']:
        return 0
    else:
        return row['REF_x']

In [4]:
df = read_vcf('/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.vcf') #vcf file from original variant calling of 1 individual

df.head(30)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1"
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1"
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10"
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10"
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE..."
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND..."
6,Human,121,.,C,G,49314,PASS,"DP=3853;AF=0.998962;SB=0;DP4=0,0,3779,70"
7,Human,209,.,C,G,2469,PASS,"DP=4542;AF=0.109203;SB=2;DP4=3584,459,436,60"
8,Human,237,.,G,GC,49314,PASS,"DP=4988;AF=0.966921;SB=14;DP4=164,21,3988,835;..."
9,Human,270,.,C,CG,49314,PASS,"DP=5712;AF=0.945553;SB=6;DP4=242,88,4122,1279;..."
10,Human,275,.,C,CG,49314,PASS,"DP=5882;AF=0.937946;SB=16;DP4=327,82,4131,1386..."
11,Human,284,.,A,AC,49314,PASS,"DP=6096;AF=0.960138;SB=15;DP4=185,91,4284,1569..."
12,Human,363,.,G,GT,49314,PASS,"DP=8340;AF=0.905516;SB=212;DP4=356,457,4641,29..."
13,Human,386,.,T,TGGCAA,1570,PASS,"DP=8821;AF=0.100669;SB=15;DP4=846,550,497,391;..."
14,Human,386,.,T,TGGCC,49314,PASS,"DP=8821;AF=0.736424;SB=28;DP4=846,550,3631,286..."
15,Human,419,.,C,CGT,49314,PASS,"DP=9087;AF=0.925278;SB=58;DP4=376,203,4596,381..."
16,Human,517,.,G,GC,1342,PASS,"DP=9644;AF=0.940377;SB=9;DP4=335,308,5013,4056..."
17,Human,522,.,C,CG,80,PASS,"DP=9616;AF=0.933548;SB=4;DP4=371,327,4948,4029..."
18,Human,524,.,C,G,2561,PASS,"DP=9769;AF=0.980755;SB=2;DP4=98,88,5292,4289"
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428..."
20,Human,560,.,C,G,49314,PASS,"DP=10142;AF=0.970321;SB=1;DP4=131,120,5289,4600"
21,Human,561,.,G,GT,49314,PASS,"DP=10062;AF=0.939873;SB=0;DP4=358,309,5044,441..."
22,Human,623,.,C,CT,49314,PASS,"DP=9760;AF=0.930635;SB=15;DP4=308,318,4878,420..."
23,Human,626,.,T,G,49314,PASS,"DP=9824;AF=0.820338;SB=0;DP4=866,767,4291,3833"
24,Human,633,.,GT,G,529,PASS,"DP=9666;AF=0.052245;SB=10;DP4=4846,4397,284,22..."
25,Human,673,.,G,C,49314,PASS,"DP=9588;AF=0.953275;SB=139;DP4=2,56,4744,4782"
26,Human,674,.,C,G,49314,PASS,"DP=9589;AF=0.993430;SB=7;DP4=2,7,4748,4827"
27,Human,749,.,T,G,17396,PASS,"DP=9674;AF=0.175109;SB=2;DP4=3837,4130,802,892"
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3..."
29,Human,850,.,C,T,13069,PASS,"DP=10063;AF=0.104740;SB=0;DP4=4144,4858,485,569"

In [5]:
df[df['REF'].str.len() > 1] #checks for reference alleles having more than 1 base. Why does lofreq report 'REF' this way?

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND..."
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428..."
24,Human,633,.,GT,G,529,PASS,"DP=9666;AF=0.052245;SB=10;DP4=4846,4397,284,22..."
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3..."
31,Human,963,.,TGAGAC,T,394,PASS,"DP=9244;AF=0.008979;SB=14;DP4=4474,4750,50,33;..."
...,...,...,...,...,...,...,...,...
318,Human,11069,.,GC,G,28436,PASS,"DP=2541;AF=0.935852;SB=2;DP4=66,133,838,1540;I..."
323,Human,11118,.,GC,G,17778,PASS,"DP=2197;AF=0.863450;SB=0;DP4=161,173,931,966;I..."
329,Human,11268,.,CG,C,19335,PASS,"DP=3057;AF=0.718024;SB=1045;DP4=790,104,1061,1..."
333,Human,11417,.,GGCA,G,3864,PASS,"DP=3769;AF=0.205890;SB=0;DP4=1936,1082,496,280..."
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND..."

In [6]:
df[(df['REF'].str.len()) > (df['ALT'].str.len())] #deletion instances

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND..."
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428..."
24,Human,633,.,GT,G,529,PASS,"DP=9666;AF=0.052245;SB=10;DP4=4846,4397,284,22..."
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3..."
31,Human,963,.,TGAGAC,T,394,PASS,"DP=9244;AF=0.008979;SB=14;DP4=4474,4750,50,33;..."
...,...,...,...,...,...,...,...,...
318,Human,11069,.,GC,G,28436,PASS,"DP=2541;AF=0.935852;SB=2;DP4=66,133,838,1540;I..."
323,Human,11118,.,GC,G,17778,PASS,"DP=2197;AF=0.863450;SB=0;DP4=161,173,931,966;I..."
329,Human,11268,.,CG,C,19335,PASS,"DP=3057;AF=0.718024;SB=1045;DP4=790,104,1061,1..."
333,Human,11417,.,GGCA,G,3864,PASS,"DP=3769;AF=0.205890;SB=0;DP4=1936,1082,496,280..."
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND..."

In [7]:
df[(df['REF'].str.len()) < (df['ALT'].str.len())] #insertion instances

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE..."
8,Human,237,.,G,GC,49314,PASS,"DP=4988;AF=0.966921;SB=14;DP4=164,21,3988,835;..."
9,Human,270,.,C,CG,49314,PASS,"DP=5712;AF=0.945553;SB=6;DP4=242,88,4122,1279;..."
10,Human,275,.,C,CG,49314,PASS,"DP=5882;AF=0.937946;SB=16;DP4=327,82,4131,1386..."
11,Human,284,.,A,AC,49314,PASS,"DP=6096;AF=0.960138;SB=15;DP4=185,91,4284,1569..."
...,...,...,...,...,...,...,...,...
372,Human,13113,.,C,CG,46985,PASS,"DP=2411;AF=0.950643;SB=164;DP4=66,78,344,1948;..."
373,Human,13150,.,A,AC,49314,PASS,"DP=2781;AF=0.961884;SB=10;DP4=11,103,152,2523;..."
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND..."
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL..."
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H..."

In [8]:
#extracting AF into a seperate column
df['AF'] = df['INFO'].apply(extract_af)

df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1",1.000000
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1",1.000000
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10",0.996952
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10",0.999624
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
...,...,...,...,...,...,...,...,...,...
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND...",0.944088
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL...",0.909971
377,Human,13280,.,G,C,13572,PASS,"DP=1017;AF=1.000000;SB=0;DP4=0,0,2,1015",1.000000
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H...",0.913212

In [9]:
type(df.loc[2, 'AF']) #string type

str

In [10]:
df['AF'] = df['AF'].astype(float) #converting format to float

type(df.loc[2, 'AF'])

numpy.float64

In [11]:
filtered_df = df[df['AF'] > 0.5] #filtering for AF threshold >0.5; extracting majority alleles at each position from variant calling

filtered_df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1",1.000000
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1",1.000000
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10",0.996952
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10",0.999624
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
...,...,...,...,...,...,...,...,...,...
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND...",0.944088
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL...",0.909971
377,Human,13280,.,G,C,13572,PASS,"DP=1017;AF=1.000000;SB=0;DP4=0,0,2,1015",1.000000
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H...",0.913212

In [12]:
temp_deletion = filtered_df[(filtered_df['REF'].str.len()) > (filtered_df['ALT'].str.len())] # deletion instances that matter

display(temp_deletion)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND...",0.987559
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428...",0.957346
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3...",0.649318
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132
58,Human,1756,.,GT,G,49314,PASS,"DP=8493;AF=0.947604;SB=0;DP4=217,287,3509,4539...",0.947604
81,Human,2486,.,TGCG,T,49314,PASS,"DP=8024;AF=0.542124;SB=3;DP4=1762,1936,2033,23...",0.542124
103,Human,3152,.,GC,G,49314,PASS,"DP=3938;AF=0.949975;SB=23;DP4=73,155,1555,2186...",0.949975
111,Human,3411,.,GC,G,49314,PASS,"DP=5172;AF=0.728925;SB=0;DP4=998,426,2634,1136...",0.728925
157,Human,5293,.,AG,A,49314,PASS,"DP=8637;AF=0.957393;SB=32;DP4=245,197,3874,439...",0.957393
158,Human,5303,.,CG,C,49314,PASS,"DP=8804;AF=0.950704;SB=36;DP4=187,295,3975,439...",0.950704
179,Human,5891,.,TG,T,49314,PASS,"DP=5347;AF=0.602768;SB=180;DP4=867,446,1667,15...",0.602768
200,Human,6534,.,TGGGC,T,49314,PASS,"DP=7090;AF=0.596474;SB=0;DP4=1353,871,2578,165...",0.596474
224,Human,7321,.,TC,T,49314,PASS,"DP=4562;AF=0.922841;SB=112;DP4=86,337,1540,267...",0.922841
225,Human,7362,.,CG,C,49314,PASS,"DP=4016;AF=0.938994;SB=6;DP4=104,163,1333,2438...",0.938994
226,Human,7369,.,TC,T,49314,PASS,"DP=4009;AF=0.836368;SB=186;DP4=344,340,1070,22...",0.836368
318,Human,11069,.,GC,G,28436,PASS,"DP=2541;AF=0.935852;SB=2;DP4=66,133,838,1540;I...",0.935852
323,Human,11118,.,GC,G,17778,PASS,"DP=2197;AF=0.863450;SB=0;DP4=161,173,931,966;I...",0.863450
329,Human,11268,.,CG,C,19335,PASS,"DP=3057;AF=0.718024;SB=1045;DP4=790,104,1061,1...",0.718024
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411

In [13]:
# Applying the function to each row
temp_deletion['Deletions'] = temp_deletion.apply(find_deletions, axis=1)

# Exploding the list to have each deletion in a separate row
deletions_expanded = temp_deletion.explode('Deletions')
deletions_expanded[['Delete_Position', 'Base']] = pd.DataFrame(deletions_expanded['Deletions'].tolist(), index=deletions_expanded.index)

display(deletions_expanded)

/var/folders/hb/l21bg8lx3tgc5ky3s56cwdth0000gn/T/ipykernel_29326/2052078697.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_deletion['Deletions'] = temp_deletion.apply(find_deletions, axis=1)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF,Deletions,Delete_Position,Base
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND...",0.987559,"(104, C)",104,C
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428...",0.957346,"(538, G)",538,G
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3...",0.649318,"(764, G)",764,G
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3...",0.649318,"(765, G)",765,G
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132,"(1672, C)",1672,C
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132,"(1673, T)",1673,T
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132,"(1674, C)",1674,C
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132,"(1675, C)",1675,C
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132,"(1676, C)",1676,C
58,Human,1756,.,GT,G,49314,PASS,"DP=8493;AF=0.947604;SB=0;DP4=217,287,3509,4539...",0.947604,"(1757, T)",1757,T
81,Human,2486,.,TGCG,T,49314,PASS,"DP=8024;AF=0.542124;SB=3;DP4=1762,1936,2033,23...",0.542124,"(2487, G)",2487,G
81,Human,2486,.,TGCG,T,49314,PASS,"DP=8024;AF=0.542124;SB=3;DP4=1762,1936,2033,23...",0.542124,"(2488, C)",2488,C
81,Human,2486,.,TGCG,T,49314,PASS,"DP=8024;AF=0.542124;SB=3;DP4=1762,1936,2033,23...",0.542124,"(2489, G)",2489,G
103,Human,3152,.,GC,G,49314,PASS,"DP=3938;AF=0.949975;SB=23;DP4=73,155,1555,2186...",0.949975,"(3153, C)",3153,C
111,Human,3411,.,GC,G,49314,PASS,"DP=5172;AF=0.728925;SB=0;DP4=998,426,2634,1136...",0.728925,"(3412, C)",3412,C
157,Human,5293,.,AG,A,49314,PASS,"DP=8637;AF=0.957393;SB=32;DP4=245,197,3874,439...",0.957393,"(5294, G)",5294,G
158,Human,5303,.,CG,C,49314,PASS,"DP=8804;AF=0.950704;SB=36;DP4=187,295,3975,439...",0.950704,"(5304, G)",5304,G
179,Human,5891,.,TG,T,49314,PASS,"DP=5347;AF=0.602768;SB=180;DP4=867,446,1667,15...",0.602768,"(5892, G)",5892,G
200,Human,6534,.,TGGGC,T,49314,PASS,"DP=7090;AF=0.596474;SB=0;DP4=1353,871,2578,165...",0.596474,"(6535, G)",6535,G
200,Human,6534,.,TGGGC,T,49314,PASS,"DP=7090;AF=0.596474;SB=0;DP4=1353,871,2578,165...",0.596474,"(6536, G)",6536,G
200,Human,6534,.,TGGGC,T,49314,PASS,"DP=7090;AF=0.596474;SB=0;DP4=1353,871,2578,165...",0.596474,"(6537, G)",6537,G
200,Human,6534,.,TGGGC,T,49314,PASS,"DP=7090;AF=0.596474;SB=0;DP4=1353,871,2578,165...",0.596474,"(6538, C)",6538,C
224,Human,7321,.,TC,T,49314,PASS,"DP=4562;AF=0.922841;SB=112;DP4=86,337,1540,267...",0.922841,"(7322, C)",7322,C
225,Human,7362,.,CG,C,49314,PASS,"DP=4016;AF=0.938994;SB=6;DP4=104,163,1333,2438...",0.938994,"(7363, G)",7363,G
226,Human,7369,.,TC,T,49314,PASS,"DP=4009;AF=0.836368;SB=186;DP4=344,340,1070,22...",0.836368,"(7370, C)",7370,C
318,Human,11069,.,GC,G,28436,PASS,"DP=2541;AF=0.935852;SB=2;DP4=66,133,838,1540;I...",0.935852,"(11070, C)",11070,C
323,Human,11118,.,GC,G,17778,PASS,"DP=2197;AF=0.863450;SB=0;DP4=161,173,931,966;I...",0.863450,"(11119, C)",11119,C
329,Human,11268,.,CG,C,19335,PASS,"DP=3057;AF=0.718024;SB=1045;DP4=790,104,1061,1...",0.718024,"(11269, G)",11269,G
375,Human,13235,.,GC,G,35659,PASS,"DP=1803;AF=0.953411;SB=22;DP4=5,91,18,1701;IND...",0.953411,"(13236, C)",13236,C

In [14]:
filtered_df[(filtered_df['REF'].str.len()) < (filtered_df['ALT'].str.len())] # insertion instances that matter

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
8,Human,237,.,G,GC,49314,PASS,"DP=4988;AF=0.966921;SB=14;DP4=164,21,3988,835;...",0.966921
9,Human,270,.,C,CG,49314,PASS,"DP=5712;AF=0.945553;SB=6;DP4=242,88,4122,1279;...",0.945553
10,Human,275,.,C,CG,49314,PASS,"DP=5882;AF=0.937946;SB=16;DP4=327,82,4131,1386...",0.937946
11,Human,284,.,A,AC,49314,PASS,"DP=6096;AF=0.960138;SB=15;DP4=185,91,4284,1569...",0.960138
12,Human,363,.,G,GT,49314,PASS,"DP=8340;AF=0.905516;SB=212;DP4=356,457,4641,29...",0.905516
14,Human,386,.,T,TGGCC,49314,PASS,"DP=8821;AF=0.736424;SB=28;DP4=846,550,3631,286...",0.736424
15,Human,419,.,C,CGT,49314,PASS,"DP=9087;AF=0.925278;SB=58;DP4=376,203,4596,381...",0.925278
16,Human,517,.,G,GC,1342,PASS,"DP=9644;AF=0.940377;SB=9;DP4=335,308,5013,4056...",0.940377
17,Human,522,.,C,CG,80,PASS,"DP=9616;AF=0.933548;SB=4;DP4=371,327,4948,4029...",0.933548
21,Human,561,.,G,GT,49314,PASS,"DP=10062;AF=0.939873;SB=0;DP4=358,309,5044,441...",0.939873
22,Human,623,.,C,CT,49314,PASS,"DP=9760;AF=0.930635;SB=15;DP4=308,318,4878,420...",0.930635
167,Human,5680,.,C,CG,49314,PASS,"DP=6883;AF=0.960918;SB=3;DP4=121,185,2471,4143...",0.960918
168,Human,5692,.,C,CG,49314,PASS,"DP=6587;AF=0.970548;SB=0;DP4=93,150,2480,3913;...",0.970548
207,Human,6791,.,G,GC,49314,PASS,"DP=7269;AF=0.928876;SB=1;DP4=251,298,3043,3709...",0.928876
215,Human,7025,.,G,GCCCGC,49314,PASS,"DP=5887;AF=0.812978;SB=38;DP4=478,374,3018,176...",0.812978
235,Human,7512,.,C,CCGGCCG,3853,PASS,"DP=3804;AF=0.661935;SB=2;DP4=453,525,1143,1375...",0.661935
248,Human,8065,.,C,CGCG,49314,PASS,"DP=7465;AF=0.874213;SB=39;DP4=549,430,4083,244...",0.874213
249,Human,8178,.,G,GCCC,49314,PASS,"DP=7565;AF=0.897555;SB=1;DP4=344,443,2924,3866...",0.897555
251,Human,8187,.,C,CCGG,49314,PASS,"DP=7771;AF=0.912109;SB=31;DP4=318,335,2964,412...",0.912109
258,Human,8688,.,C,CCCGT,49314,PASS,"DP=6180;AF=0.522977;SB=130;DP4=883,1870,1338,1...",0.522977
314,Human,10881,.,C,CCG,7384,PASS,"DP=5587;AF=0.823877;SB=41;DP4=308,704,1121,348...",0.823877
315,Human,10931,.,A,AC,49314,PASS,"DP=5410;AF=0.891682;SB=290;DP4=253,370,933,389...",0.891682
317,Human,11033,.,C,CG,49314,PASS,"DP=3449;AF=0.938533;SB=10;DP4=73,184,1095,2142...",0.938533
321,Human,11101,.,A,AC,13024,PASS,"DP=2284;AF=0.831874;SB=67;DP4=174,127,789,1111...",0.831874
322,Human,11104,.,T,TC,11790,PASS,"DP=2303;AF=0.809379;SB=35;DP4=239,213,806,1058...",0.809379
330,Human,11293,.,C,CG,37222,PASS,"DP=3028;AF=0.898613;SB=103;DP4=253,81,1562,115...",0.898613
335,Human,11485,.,C,CG,49314,PASS,"DP=5216;AF=0.963382;SB=10;DP4=123,78,3361,1664...",0.963382
337,Human,11936,.,G,GC,49314,PASS,"DP=6220;AF=0.958039;SB=26;DP4=147,134,2557,340...",0.958039
344,Human,12011,.,G,GC,49314,PASS,"DP=5272;AF=0.879742;SB=595;DP4=210,470,2975,16...",0.879742
347,Human,12046,.,G,GGCCGCGC,3181,PASS,"DP=5809;AF=0.560337;SB=2147483647;DP4=612,1883...",0.560337
355,Human,12624,.,C,CG,49314,PASS,"DP=7901;AF=0.944184;SB=50;DP4=201,307,3719,374...",0.944184
361,Human,12722,.,C,CGCG,49314,PASS,"DP=6147;AF=0.886449;SB=7;DP4=191,275,2067,3382...",0.886449
367,Human,12998,.,C,CG,49314,PASS,"DP=3437;AF=0.953157;SB=8;DP4=78,113,1518,1758;...",0.953157
369,Human,13068,.,C,CG,28541,PASS,"DP=2504;AF=0.763179;SB=436;DP4=64,526,761,1150...",0.763179
370,Human,13079,.,T,TG,11689,PASS,"DP=2464;AF=0.508117;SB=138;DP4=248,953,432,820...",0.508117
372,Human,13113,.,C,CG,46985,PASS,"DP=2411;AF=0.950643;SB=164;DP4=66,78,344,1948;...",0.950643
373,Human,13150,.,A,AC,49314,PASS,"DP=2781;AF=0.961884;SB=10;DP4=11,103,152,2523;...",0.961884
374,Human,13219,.,C,CG,43670,PASS,"DP=2182;AF=0.944088;SB=1;DP4=1,152,29,2031;IND...",0.944088
376,Human,13278,.,G,GGC,13133,PASS,"DP=1033;AF=0.909971;SB=0;DP4=0,103,2,938;INDEL...",0.909971
378,Human,13288,.,G,GC,9834,PASS,"DP=772;AF=0.913212;SB=6;DP4=1,94,1,704;INDEL;H...",0.913212

In [15]:
#alt way to read vcf files filtered for variant positions
# filter_vcf('/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.vcf') #similar outputs to the pandas filter

In [16]:
mpileup_file_path = '/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.mpileup' #extracting reference alleles for all Positions

mpileup_df = pd.read_csv(mpileup_file_path, sep='\t', header=None, usecols=[0, 1, 2], names=['CHROM', 'POS', 'REF'])

mpileup_df.head(32)

    CHROM  POS REF
0   Human    1   G
1   Human    2   C
2   Human    3   T
3   Human    4   G
4   Human    5   A
5   Human    6   C
6   Human    7   A
7   Human    8   C
8   Human    9   G
9   Human   10   C
10  Human   11   T
11  Human   12   G
12  Human   13   T
13  Human   14   C
14  Human   15   C
15  Human   16   T
16  Human   17   C
17  Human   18   T
18  Human   19   G
19  Human   20   G
20  Human   21   C
21  Human   22   G
22  Human   23   A
23  Human   24   C
24  Human   25   C
25  Human   26   T
26  Human   27   G
27  Human   28   T
28  Human   29   C
29  Human   30   G
30  Human   31   T
31  Human   32   C

In [17]:
mpileup_df.shape

(13314, 3)

In [18]:
mpileup_df[mpileup_df['REF'].str.len() > 1] #checking each reference position has 1 base

Empty DataFrame
Columns: [CHROM, POS, REF]
Index: []

In [19]:
merged_df = mpileup_df.merge(filtered_df[['POS', 'ALT']], on='POS', how='left') #merge with filtered_df i.e. alt(majority) alleles at each position from variant calling

merged_df.head(563)

     CHROM  POS REF  ALT
0    Human    1   G  NaN
1    Human    2   C  NaN
2    Human    3   T  NaN
3    Human    4   G  NaN
4    Human    5   A  NaN
..     ...  ...  ..  ...
558  Human  559   C  NaN
559  Human  560   C    G
560  Human  561   G   GT
561  Human  562   G  NaN
562  Human  563   C  NaN

[563 rows x 4 columns]

In [20]:
merged_df['REF'] = merged_df.apply(lambda row: row['ALT'] if pd.notnull(row['ALT']) else row['REF'], axis=1) #replace ref values w alt values if not NaN

merged_df.head(104)

     CHROM  POS REF  ALT
0    Human    1   G  NaN
1    Human    2   C  NaN
2    Human    3   T  NaN
3    Human    4   G  NaN
4    Human    5   A  NaN
..     ...  ...  ..  ...
99   Human  100   C  NaN
100  Human  101   C  NaN
101  Human  102   T  NaN
102  Human  103   G    G
103  Human  104   C  NaN

[104 rows x 4 columns]

In [21]:
# Merge on the position columns, ensuring that deletions_expanded aligns with merged_df
merged_df = pd.merge(merged_df, deletions_expanded, left_on='POS', right_on='Delete_Position', how='left')
        
display(merged_df)

,CHROM_x,POS_x,REF_x,ALT_x,CHROM_y,POS_y,ID,REF_y,ALT_y,QUAL,FILTER,INFO,AF,Deletions,Delete_Position,Base
0,Human,1,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Human,2,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Human,3,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Human,4,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Human,5,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13309,Human,13310,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13310,Human,13311,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13311,Human,13312,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13312,Human,13313,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13313,Human,13314,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
merged_df['REF_x'] = merged_df.apply(replace_ref, axis=1)

In [ ]:
merged_df.drop(['ALT_x', 'CHROM_y', 'POS_y', 'ID', 'REF_y', 'ALT_y', 'QUAL', 'FILTER', 'INFO', 'AF', 'Deletions', 'Delete_Position', 'Base'] , axis=1, inplace=True)

merged_df

In [34]:
merged_df.rename(columns={'CHROM_x':'CHROM', 'POS_x':'POS', 'REF_x':'REF'}, inplace=True)

merged_df[merged_df['REF']==0].shape #CHECKS

(29, 3)

In [25]:
# merged_df.to_csv('reference.csv', index=False)

In [ ]:
#alt way to get reference enumerated
df_fasta = fasta_to_all_chars_dataframe('/Users/fionachow/Documents/rDNA_prototype_prerRNA_only.fa') #manually deleted first line of header

print(df_fasta.head())
print(df_fasta.shape)

In [ ]:
assert mpileup_df['POS'].equals(df_fasta['POS']) and mpileup_df['REF'].equals(df_fasta['REF']) #checks my workaround matches enumerating reference file