In [6280]:
import pandas as pd
import regex as re
import io

In [6281]:
def read_vcf(path):
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    match = re.search(r'AF=([\d\.]+)', info)
    return match.group(1) if match else None

In [6282]:
df = read_vcf('/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.vcf') #vcf file from original variant calling of 1 individual
df['AF'] = df['INFO'].apply(extract_af)

df.head(60)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,AF
0,Human,31,.,T,C,21247,PASS,"DP=1510;AF=1.000000;SB=0;DP4=0,0,1509,1",1.000000
1,Human,32,.,C,T,22076,PASS,"DP=1554;AF=1.000000;SB=0;DP4=0,0,1553,1",1.000000
2,Human,73,.,C,A,46496,PASS,"DP=2625;AF=0.996952;SB=0;DP4=7,0,2607,10",0.996952
3,Human,74,.,A,C,48045,PASS,"DP=2657;AF=0.999624;SB=0;DP4=1,0,2646,10",0.999624
4,Human,80,.,A,AC,49314,PASS,"DP=2829;AF=0.977024;SB=0;DP4=64,0,2747,17;INDE...",0.977024
5,Human,103,.,GC,G,49314,PASS,"DP=3376;AF=0.987559;SB=31;DP4=38,4,3304,30;IND...",0.987559
6,Human,121,.,C,G,49314,PASS,"DP=3853;AF=0.998962;SB=0;DP4=0,0,3779,70",0.998962
7,Human,209,.,C,G,2469,PASS,"DP=4542;AF=0.109203;SB=2;DP4=3584,459,436,60",0.109203
8,Human,237,.,G,GC,49314,PASS,"DP=4988;AF=0.966921;SB=14;DP4=164,21,3988,835;...",0.966921
9,Human,270,.,C,CG,49314,PASS,"DP=5712;AF=0.945553;SB=6;DP4=242,88,4122,1279;...",0.945553
10,Human,275,.,C,CG,49314,PASS,"DP=5882;AF=0.937946;SB=16;DP4=327,82,4131,1386...",0.937946
11,Human,284,.,A,AC,49314,PASS,"DP=6096;AF=0.960138;SB=15;DP4=185,91,4284,1569...",0.960138
12,Human,363,.,G,GT,49314,PASS,"DP=8340;AF=0.905516;SB=212;DP4=356,457,4641,29...",0.905516
13,Human,386,.,T,TGGCAA,1570,PASS,"DP=8821;AF=0.100669;SB=15;DP4=846,550,497,391;...",0.100669
14,Human,386,.,T,TGGCC,49314,PASS,"DP=8821;AF=0.736424;SB=28;DP4=846,550,3631,286...",0.736424
15,Human,419,.,C,CGT,49314,PASS,"DP=9087;AF=0.925278;SB=58;DP4=376,203,4596,381...",0.925278
16,Human,517,.,G,GC,1342,PASS,"DP=9644;AF=0.940377;SB=9;DP4=335,308,5013,4056...",0.940377
17,Human,522,.,C,CG,80,PASS,"DP=9616;AF=0.933548;SB=4;DP4=371,327,4948,4029...",0.933548
18,Human,524,.,C,G,2561,PASS,"DP=9769;AF=0.980755;SB=2;DP4=98,88,5292,4289",0.980755
19,Human,537,.,TG,T,49314,PASS,"DP=9753;AF=0.957346;SB=86;DP4=310,144,5049,428...",0.957346
20,Human,560,.,C,G,49314,PASS,"DP=10142;AF=0.970321;SB=1;DP4=131,120,5289,4600",0.970321
21,Human,561,.,G,GT,49314,PASS,"DP=10062;AF=0.939873;SB=0;DP4=358,309,5044,441...",0.939873
22,Human,623,.,C,CT,49314,PASS,"DP=9760;AF=0.930635;SB=15;DP4=308,318,4878,420...",0.930635
23,Human,626,.,T,G,49314,PASS,"DP=9824;AF=0.820338;SB=0;DP4=866,767,4291,3833",0.820338
24,Human,633,.,GT,G,529,PASS,"DP=9666;AF=0.052245;SB=10;DP4=4846,4397,284,22...",0.052245
25,Human,673,.,G,C,49314,PASS,"DP=9588;AF=0.953275;SB=139;DP4=2,56,4744,4782",0.953275
26,Human,674,.,C,G,49314,PASS,"DP=9589;AF=0.993430;SB=7;DP4=2,7,4748,4827",0.993430
27,Human,749,.,T,G,17396,PASS,"DP=9674;AF=0.175109;SB=2;DP4=3837,4130,802,892",0.175109
28,Human,763,.,CGG,C,49314,PASS,"DP=9684;AF=0.649318;SB=75;DP4=1732,1687,2816,3...",0.649318
29,Human,850,.,C,T,13069,PASS,"DP=10063;AF=0.104740;SB=0;DP4=4144,4858,485,569",0.104740
30,Human,878,.,G,A,217,PASS,"DP=10015;AF=0.011083;SB=0;DP4=4662,5235,51,60",0.011083
31,Human,963,.,TGAGAC,T,394,PASS,"DP=9244;AF=0.008979;SB=14;DP4=4474,4750,50,33;...",0.008979
32,Human,1037,.,C,CT,169,PASS,"DP=8942;AF=0.006934;SB=4;DP4=4524,4403,35,27;I...",0.006934
33,Human,1092,.,GGT,G,944,PASS,"DP=9231;AF=0.012566;SB=0;DP4=4682,4484,59,57;I...",0.012566
34,Human,1103,.,T,G,86,PASS,"DP=9358;AF=0.024364;SB=19;DP4=4659,4446,138,93",0.024364
35,Human,1143,.,A,C,310,PASS,"DP=9608;AF=0.036428;SB=370;DP4=4901,4282,68,283",0.036428
36,Human,1148,.,T,TC,98,PASS,"DP=9607;AF=0.004996;SB=0;DP4=5034,4596,25,23;I...",0.004996
37,Human,1148,.,T,G,323,PASS,"DP=9678;AF=0.039884;SB=15;DP4=4869,4395,180,206",0.039884
38,Human,1151,.,T,G,1472,PASS,"DP=9754;AF=0.094833;SB=418;DP4=4824,3997,289,636",0.094833
39,Human,1153,.,T,G,1083,PASS,"DP=9807;AF=0.086673;SB=175;DP4=4804,4133,324,526",0.086673
40,Human,1155,.,T,G,1263,PASS,"DP=9808;AF=0.079425;SB=670;DP4=4931,4089,178,601",0.079425
41,Human,1163,.,C,T,25134,PASS,"DP=9801;AF=0.225589;SB=7;DP4=3932,3498,1132,1079",0.225589
42,Human,1207,.,G,C,997,PASS,"DP=9819;AF=0.022813;SB=5;DP4=5142,4435,138,102",0.022813
43,Human,1213,.,C,CT,200,PASS,"DP=9718;AF=0.005557;SB=4;DP4=5213,4520,25,29;I...",0.005557
44,Human,1279,.,C,G,2673,PASS,"DP=9945;AF=0.033384;SB=1;DP4=5013,4594,169,163",0.033384
45,Human,1280,.,C,G,7470,PASS,"DP=9892;AF=0.065204;SB=2;DP4=4822,4413,349,302",0.065204
46,Human,1313,.,C,G,133,PASS,"DP=9865;AF=0.007400;SB=11;DP4=5150,4639,31,43",0.007400
47,Human,1498,.,G,GT,11266,PASS,"DP=10297;AF=0.053996;SB=1;DP4=4543,5233,255,30...",0.053996
48,Human,1578,.,A,C,91,PASS,"DP=9493;AF=0.028547;SB=324;DP4=4345,4864,225,46",0.028547
49,Human,1608,.,C,T,10833,PASS,"DP=9106;AF=0.093675;SB=6;DP4=4036,4202,400,453",0.093675
50,Human,1612,.,C,CT,14453,PASS,"DP=8964;AF=0.084672;SB=3;DP4=4003,4269,355,404...",0.084672
51,Human,1626,.,T,TC,35112,PASS,"DP=8691;AF=0.175584;SB=0;DP4=3492,3740,735,791...",0.175584
52,Human,1671,.,GC,G,1432,PASS,"DP=7755;AF=0.031593;SB=44;DP4=1326,1605,145,10...",0.031593
53,Human,1671,.,GCTCCC,G,12978,PASS,"DP=7755;AF=0.596132;SB=1;DP4=1326,1605,2116,25...",0.596132
54,Human,1673,.,TCCCA,T,49314,PASS,"DP=7762;AF=0.318475;SB=27;DP4=2510,2834,1067,1...",0.318475
55,Human,1677,.,A,T,304,PASS,"DP=7968;AF=0.632530;SB=64;DP4=207,136,2322,2718",0.632530
56,Human,1709,.,C,T,935,PASS,"DP=8128;AF=0.021407;SB=7;DP4=3523,4421,68,106",0.021407
57,Human,1749,.,C,T,49314,PASS,"DP=8478;AF=0.570535;SB=11;DP4=1543,2085,2154,2683",0.570535
58,Human,1756,.,GT,G,49314,PASS,"DP=8493;AF=0.947604;SB=0;DP4=217,287,3509,4539...",0.947604
59,Human,1930,.,C,CG,94,PASS,"DP=7886;AF=0.005833;SB=1;DP4=4342,3554,24,22;I...",0.005833

In [6283]:
type(df['AF'].iloc[0])

str

In [6284]:
#get sequnce of individual at each position
og_ref = pd.read_csv('/Users/fionachow/Documents/NYU/CDS/Summer 2024/Human rDNA Research/Project/Human-rDNA/outputs/src_outputs/og_ref.csv')

og_ref.shape

(13314, 3)

In [6285]:
type(og_ref['POS'].iloc[30])

numpy.int64

In [6286]:
new_ref = pd.read_csv('/Users/fionachow/Documents/NYU/CDS/Summer 2024/Human rDNA Research/Project/Human-rDNA/outputs/src_outputs/1000_genome_new_ref/1000_genome_new_ref_v2.csv')

new_ref.shape

(13314, 3)

In [6287]:
df = df[['POS', 'REF', 'ALT', 'AF']]  

print(og_ref.columns)
print(df.columns)

merged_df = pd.merge(og_ref, df, on='POS', how='left', suffixes=('_og', '_vcf'))

merged_df.rename(columns={'REF_og':'ALT_og', 'ALT':'ALT_vcf'}, inplace=True)

merged_df.head(33)

Index(['POS', 'Type', 'REF'], dtype='object')
Index(['POS', 'REF', 'ALT', 'AF'], dtype='object')

    POS      Type ALT_og REF_vcf ALT_vcf        AF
0     1  sequence      G     NaN     NaN       NaN
1     2  sequence      C     NaN     NaN       NaN
2     3  sequence      T     NaN     NaN       NaN
3     4  sequence      G     NaN     NaN       NaN
4     5  sequence      A     NaN     NaN       NaN
5     6  sequence      C     NaN     NaN       NaN
6     7  sequence      A     NaN     NaN       NaN
7     8  sequence      C     NaN     NaN       NaN
8     9  sequence      G     NaN     NaN       NaN
9    10  sequence      C     NaN     NaN       NaN
10   11  sequence      T     NaN     NaN       NaN
11   12  sequence      G     NaN     NaN       NaN
12   13  sequence      T     NaN     NaN       NaN
13   14  sequence      C     NaN     NaN       NaN
14   15  sequence      C     NaN     NaN       NaN
15   16  sequence      T     NaN     NaN       NaN
16   17  sequence      C     NaN     NaN       NaN
17   18  sequence      T     NaN     NaN       NaN
18   19  sequence      G     NaN     NaN       NaN
19   20  sequence      G     NaN     NaN       NaN
20   21  sequence      C     NaN     NaN       NaN
21   22  sequence      G     NaN     NaN       NaN
22   23  sequence      A     NaN     NaN       NaN
23   24  sequence      C     NaN     NaN       NaN
24   25  sequence      C     NaN     NaN       NaN
25   26  sequence      T     NaN     NaN       NaN
26   27  sequence      G     NaN     NaN       NaN
27   28  sequence      T     NaN     NaN       NaN
28   29  sequence      C     NaN     NaN       NaN
29   30  sequence      G     NaN     NaN       NaN
30   31  sequence      T       T       C  1.000000
31   32  sequence      C       C       T  1.000000
32   33  sequence      G     NaN     NaN       NaN

In [6288]:
merged_df.shape

(13346, 6)

In [6289]:
merged_df['POS'].iloc[30]

31

In [6290]:
merged_df[(merged_df['POS'] - 1)!= merged_df.index]

         POS      Type ALT_og REF_vcf ALT_vcf        AF
386      386  sequence      T       T   TGGCC  0.736424
387      387  sequence      G     NaN     NaN       NaN
388      388  sequence      G     NaN     NaN       NaN
389      389  sequence      C     NaN     NaN       NaN
390      390  sequence      C     NaN     NaN       NaN
...      ...       ...    ...     ...     ...       ...
13341  13310  sequence      T     NaN     NaN       NaN
13342  13311  sequence      C     NaN     NaN       NaN
13343  13312  sequence      G     NaN     NaN       NaN
13344  13313  sequence      C     NaN     NaN       NaN
13345  13314  sequence      G     NaN     NaN       NaN

[12960 rows x 6 columns]

In [6291]:
merged_df.head(389)

     POS      Type ALT_og REF_vcf ALT_vcf        AF
0      1  sequence      G     NaN     NaN       NaN
1      2  sequence      C     NaN     NaN       NaN
2      3  sequence      T     NaN     NaN       NaN
3      4  sequence      G     NaN     NaN       NaN
4      5  sequence      A     NaN     NaN       NaN
..   ...       ...    ...     ...     ...       ...
384  385  sequence      C     NaN     NaN       NaN
385  386  sequence      T       T  TGGCAA  0.100669
386  386  sequence      T       T   TGGCC  0.736424
387  387  sequence      G     NaN     NaN       NaN
388  388  sequence      G     NaN     NaN       NaN

[389 rows x 6 columns]

In [6292]:
df[df['POS'] == 386]

    POS REF     ALT        AF
13  386   T  TGGCAA  0.100669
14  386   T   TGGCC  0.736424

In [6293]:
# Combine the ALT_og column and ALT_vcf into ALT_combined, and set AF to 0 where variant did not exist
merged_df['ALT_combined'] = merged_df.apply(lambda x: x['ALT_vcf'] if pd.notna(x['ALT_vcf']) else x['ALT_og'], axis=1)
merged_df['AF'] = merged_df['AF'].fillna(0) 

merged_df.head(32)

    POS      Type ALT_og REF_vcf ALT_vcf        AF ALT_combined
0     1  sequence      G     NaN     NaN         0            G
1     2  sequence      C     NaN     NaN         0            C
2     3  sequence      T     NaN     NaN         0            T
3     4  sequence      G     NaN     NaN         0            G
4     5  sequence      A     NaN     NaN         0            A
5     6  sequence      C     NaN     NaN         0            C
6     7  sequence      A     NaN     NaN         0            A
7     8  sequence      C     NaN     NaN         0            C
8     9  sequence      G     NaN     NaN         0            G
9    10  sequence      C     NaN     NaN         0            C
10   11  sequence      T     NaN     NaN         0            T
11   12  sequence      G     NaN     NaN         0            G
12   13  sequence      T     NaN     NaN         0            T
13   14  sequence      C     NaN     NaN         0            C
14   15  sequence      C     NaN     NaN         0            C
15   16  sequence      T     NaN     NaN         0            T
16   17  sequence      C     NaN     NaN         0            C
17   18  sequence      T     NaN     NaN         0            T
18   19  sequence      G     NaN     NaN         0            G
19   20  sequence      G     NaN     NaN         0            G
20   21  sequence      C     NaN     NaN         0            C
21   22  sequence      G     NaN     NaN         0            G
22   23  sequence      A     NaN     NaN         0            A
23   24  sequence      C     NaN     NaN         0            C
24   25  sequence      C     NaN     NaN         0            C
25   26  sequence      T     NaN     NaN         0            T
26   27  sequence      G     NaN     NaN         0            G
27   28  sequence      T     NaN     NaN         0            T
28   29  sequence      C     NaN     NaN         0            C
29   30  sequence      G     NaN     NaN         0            G
30   31  sequence      T       T       C  1.000000            C
31   32  sequence      C       C       T  1.000000            T

In [6294]:
merged_df.head(80)

    POS      Type ALT_og REF_vcf ALT_vcf        AF ALT_combined
0     1  sequence      G     NaN     NaN         0            G
1     2  sequence      C     NaN     NaN         0            C
2     3  sequence      T     NaN     NaN         0            T
3     4  sequence      G     NaN     NaN         0            G
4     5  sequence      A     NaN     NaN         0            A
..  ...       ...    ...     ...     ...       ...          ...
75   76  sequence      G     NaN     NaN         0            G
76   77  sequence      G     NaN     NaN         0            G
77   78  sequence      T     NaN     NaN         0            T
78   79  sequence      G     NaN     NaN         0            G
79   80  sequence      A       A      AC  0.977024           AC

[80 rows x 7 columns]

In [6295]:
merged_df.head(637)

     POS      Type ALT_og REF_vcf ALT_vcf        AF ALT_combined
0      1  sequence      G     NaN     NaN         0            G
1      2  sequence      C     NaN     NaN         0            C
2      3  sequence      T     NaN     NaN         0            T
3      4  sequence      G     NaN     NaN         0            G
4      5  sequence      A     NaN     NaN         0            A
..   ...       ...    ...     ...     ...       ...          ...
632  632  sequence      G     NaN     NaN         0            G
633  633  sequence      G      GT       G  0.052245            G
634  634  sequence      T     NaN     NaN         0            T
635  635  sequence      G     NaN     NaN         0            G
636  636  sequence      C     NaN     NaN         0            C

[637 rows x 7 columns]

In [6296]:
###to identify deletions from this table 
###-> Alt_og == Alt_vcf (get position)
###-> save position if any of subsequent positions are NaN in Alt_vcf but not Nan in Alt_og 
   ### --> add the base and position to a deletion_dictionary = {104: 'C'}

In [6297]:
merged_df.drop(columns=['ALT_vcf','Type'], inplace=True)

merged_df.rename(columns={'ALT_og': 'og_ref', 'AF':'AF_old', 'ALT_combined':'ALT_old'}, inplace=True)

merged_df.head(73)

    POS og_ref REF_vcf    AF_old ALT_old
0     1      G     NaN         0       G
1     2      C     NaN         0       C
2     3      T     NaN         0       T
3     4      G     NaN         0       G
4     5      A     NaN         0       A
..  ...    ...     ...       ...     ...
68   69      G     NaN         0       G
69   70      C     NaN         0       C
70   71      C     NaN         0       C
71   72      T     NaN         0       T
72   73      C       C  0.996952       A

[73 rows x 5 columns]

In [6298]:
type(merged_df['AF_old'].iloc[30])

str

In [6299]:
merged_df = pd.merge(merged_df, new_ref, on='POS', how='left')
merged_df.drop(columns=['Unnamed: 0'], inplace=True)
merged_df.rename(columns={'1000_genome_new_ref': 'new_ref'}, inplace=True)

merged_df

         POS og_ref REF_vcf AF_old ALT_old new_ref
0          1      G     NaN      0       G       G
1          2      C     NaN      0       C       C
2          3      T     NaN      0       T       T
3          4      G     NaN      0       G       G
4          5      A     NaN      0       A       A
...      ...    ...     ...    ...     ...     ...
13341  13310      T     NaN      0       T       T
13342  13311      C     NaN      0       C       C
13343  13312      G     NaN      0       G       G
13344  13313      C     NaN      0       C       C
13345  13314      G     NaN      0       G       G

[13346 rows x 6 columns]

In [6300]:
merged_df.head(1676)

       POS og_ref REF_vcf    AF_old ALT_old new_ref
0        1      G     NaN         0       G       G
1        2      C     NaN         0       C       C
2        3      T     NaN         0       T       T
3        4      G     NaN         0       G       G
4        5      A     NaN         0       A       A
...    ...    ...     ...       ...     ...     ...
1671  1670      C     NaN         0       C       C
1672  1671      G      GC  0.031593       G       G
1673  1671      G  GCTCCC  0.596132       G       G
1674  1672      C     NaN         0       C       0
1675  1673      T   TCCCA  0.318475       T       0

[1676 rows x 6 columns]

In [6301]:
merged_df.head(104)

     POS og_ref REF_vcf    AF_old ALT_old new_ref
0      1      G     NaN         0       G       G
1      2      C     NaN         0       C       C
2      3      T     NaN         0       T       T
3      4      G     NaN         0       G       G
4      5      A     NaN         0       A       A
..   ...    ...     ...       ...     ...     ...
99   100      C     NaN         0       C       C
100  101      C     NaN         0       C       C
101  102      T     NaN         0       T       T
102  103      G      GC  0.987559       G       G
103  104      C     NaN         0       C       0

[104 rows x 6 columns]

In [6302]:
merged_df.head(636)

     POS og_ref REF_vcf    AF_old ALT_old new_ref
0      1      G     NaN         0       G       G
1      2      C     NaN         0       C       C
2      3      T     NaN         0       T       T
3      4      G     NaN         0       G       G
4      5      A     NaN         0       A       A
..   ...    ...     ...       ...     ...     ...
631  631      G     NaN         0       G       G
632  632      G     NaN         0       G       G
633  633      G      GT  0.052245       G       G
634  634      T     NaN         0       T       T
635  635      G     NaN         0       G       G

[636 rows x 6 columns]

In [6303]:
merged_df.head(1676)

       POS og_ref REF_vcf    AF_old ALT_old new_ref
0        1      G     NaN         0       G       G
1        2      C     NaN         0       C       C
2        3      T     NaN         0       T       T
3        4      G     NaN         0       G       G
4        5      A     NaN         0       A       A
...    ...    ...     ...       ...     ...     ...
1671  1670      C     NaN         0       C       C
1672  1671      G      GC  0.031593       G       G
1673  1671      G  GCTCCC  0.596132       G       G
1674  1672      C     NaN         0       C       0
1675  1673      T   TCCCA  0.318475       T       0

[1676 rows x 6 columns]

In [6304]:
merged_df[(merged_df['new_ref'].str.len()) > (merged_df['og_ref'].str.len())]

         POS og_ref REF_vcf    AF_old      ALT_old   new_ref
79        80      A       A  0.977024           AC        AC
236      237      G       G  0.966921           GC        GC
269      270      C       C  0.945553           CG        CG
274      275      C       C  0.937946           CG        CG
283      284      A       A  0.960138           AC        AC
362      363      G       G  0.905516           GT        GT
385      386      T       T  0.100669       TGGCAA     TGGCC
386      386      T       T  0.736424        TGGCC     TGGCC
419      419      C       C  0.925278          CGT       CGT
517      517      G       G  0.940377           GC        GC
522      522      C       C  0.933548           CG        CG
561      561      G       G  0.939873           GT        GT
623      623      C       C  0.930635           CT        CT
5684    5680      C       C  0.960918           CG        CG
5696    5692      C       C  0.970548           CG        CG
6801    6791      G       G  0.928876           GC        GC
7035    7025      G       G  0.812978       GCCCGC    GCCCGC
7522    7512      C       C  0.661935      CCGGCCG   CCGGCCG
7523    7512      C       C  0.040221  CCGCCCGGCCG   CCGGCCG
8076    8065      C       C  0.874213         CGCG      CGCG
8189    8178      G       G  0.897555         GCCC      GCCC
8198    8187      C       C  0.912109         CCGG      CCGG
8699    8688      C       C  0.522977        CCCGT     CCCGT
8700    8688      C       C  0.017961    CCCGTCCGT     CCCGT
8701    8688      C       C  0.009385        CCCGG     CCCGT
8702    8688      C   CCCGT  0.009547            C     CCCGT
10905  10881      C       C  0.823877          CCG       CCG
10955  10931      A       A  0.891682           AC        AC
11057  11033      C       C  0.938533           CG        CG
11101  11077      G       G  0.339476           GC        GC
11110  11086      G       G  0.485025          GCC       GCC
11125  11101      A       A  0.831874           AC        AC
11128  11104      T       T  0.809379           TC        TC
11317  11293      C       C  0.898613           CG        CG
11510  11485      C       C  0.963382           CG        CG
11961  11936      G       G  0.958039           GC        GC
12036  12011      G       G  0.879742           GC        GC
12071  12046      G       G  0.560337     GGCCGCGC  GGCCGCGC
12652  12624      C       C  0.944184           CG        CG
12751  12722      C       C  0.044737           CG      CGCG
12752  12722      C       C  0.886449         CGCG      CGCG
13029  12998      C       C  0.953157           CG        CG
13099  13068      C       C  0.763179           CG        CG
13144  13113      C       C  0.950643           CG        CG
13181  13150      A       A  0.961884           AC        AC
13250  13219      C       C  0.944088           CG        CG
13309  13278      G       G  0.909971          GGC       GGC
13319  13288      G       G  0.913212           GC        GC

In [6305]:
filtered_df = merged_df[(merged_df['og_ref'] != merged_df['new_ref']) & (merged_df['AF_old'] != 0)]

filtered_df.shape #number of ALT rows being changed

(87, 6)

In [6306]:
filtered_df

         POS og_ref REF_vcf    AF_old ALT_old new_ref
30        31      T       T  1.000000       C       C
31        32      C       C  1.000000       T       T
72        73      C       C  0.996952       A       A
73        74      A       A  0.999624       C       C
79        80      A       A  0.977024      AC      AC
...      ...    ...     ...       ...     ...     ...
13181  13150      A       A  0.961884      AC      AC
13250  13219      C       C  0.944088      CG      CG
13309  13278      G       G  0.909971     GGC     GGC
13311  13280      G       G  1.000000       C       C
13319  13288      G       G  0.913212      GC      GC

[87 rows x 6 columns]

In [6307]:
merged_df['REF_vcf'].iloc[0]

nan

In [6308]:
#incorporating deletions iff it exists
# merged_df['new_ref'] = merged_df.apply(lambda x: x['REF_vcf'] if pd.notna(x['REF_vcf']) and (len(x['REF_vcf']) > 1)  else x['new_ref'], axis=1)

merged_df.head(1676)

       POS og_ref REF_vcf    AF_old ALT_old new_ref
0        1      G     NaN         0       G       G
1        2      C     NaN         0       C       C
2        3      T     NaN         0       T       T
3        4      G     NaN         0       G       G
4        5      A     NaN         0       A       A
...    ...    ...     ...       ...     ...     ...
1671  1670      C     NaN         0       C       C
1672  1671      G      GC  0.031593       G       G
1673  1671      G  GCTCCC  0.596132       G       G
1674  1672      C     NaN         0       C       0
1675  1673      T   TCCCA  0.318475       T       0

[1676 rows x 6 columns]

In [6309]:
merged_df.head(635)

     POS og_ref REF_vcf    AF_old ALT_old new_ref
0      1      G     NaN         0       G       G
1      2      C     NaN         0       C       C
2      3      T     NaN         0       T       T
3      4      G     NaN         0       G       G
4      5      A     NaN         0       A       A
..   ...    ...     ...       ...     ...     ...
630  630      C     NaN         0       C       C
631  631      G     NaN         0       G       G
632  632      G     NaN         0       G       G
633  633      G      GT  0.052245       G       G
634  634      T     NaN         0       T       T

[635 rows x 6 columns]

In [6310]:
merged_df.head(104)

     POS og_ref REF_vcf    AF_old ALT_old new_ref
0      1      G     NaN         0       G       G
1      2      C     NaN         0       C       C
2      3      T     NaN         0       T       T
3      4      G     NaN         0       G       G
4      5      A     NaN         0       A       A
..   ...    ...     ...       ...     ...     ...
99   100      C     NaN         0       C       C
100  101      C     NaN         0       C       C
101  102      T     NaN         0       T       T
102  103      G      GC  0.987559       G       G
103  104      C     NaN         0       C       0

[104 rows x 6 columns]

In [6311]:
#using ALT_old unless reference changed and AF_old != 0
merged_df['ALT_new'] = merged_df.apply(lambda x: x['og_ref'] if (x['AF_old'] != 0) and (x['og_ref'] != x['new_ref']) else x['ALT_old'], axis=1)

merged_df

         POS og_ref REF_vcf AF_old ALT_old new_ref ALT_new
0          1      G     NaN      0       G       G       G
1          2      C     NaN      0       C       C       C
2          3      T     NaN      0       T       T       T
3          4      G     NaN      0       G       G       G
4          5      A     NaN      0       A       A       A
...      ...    ...     ...    ...     ...     ...     ...
13341  13310      T     NaN      0       T       T       T
13342  13311      C     NaN      0       C       C       C
13343  13312      G     NaN      0       G       G       G
13344  13313      C     NaN      0       C       C       C
13345  13314      G     NaN      0       G       G       G

[13346 rows x 7 columns]

In [6312]:
merged_df.head(32)

    POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new
0     1      G     NaN         0       G       G       G
1     2      C     NaN         0       C       C       C
2     3      T     NaN         0       T       T       T
3     4      G     NaN         0       G       G       G
4     5      A     NaN         0       A       A       A
5     6      C     NaN         0       C       C       C
6     7      A     NaN         0       A       A       A
7     8      C     NaN         0       C       C       C
8     9      G     NaN         0       G       G       G
9    10      C     NaN         0       C       C       C
10   11      T     NaN         0       T       T       T
11   12      G     NaN         0       G       G       G
12   13      T     NaN         0       T       T       T
13   14      C     NaN         0       C       C       C
14   15      C     NaN         0       C       C       C
15   16      T     NaN         0       T       T       T
16   17      C     NaN         0       C       C       C
17   18      T     NaN         0       T       T       T
18   19      G     NaN         0       G       G       G
19   20      G     NaN         0       G       G       G
20   21      C     NaN         0       C       C       C
21   22      G     NaN         0       G       G       G
22   23      A     NaN         0       A       A       A
23   24      C     NaN         0       C       C       C
24   25      C     NaN         0       C       C       C
25   26      T     NaN         0       T       T       T
26   27      G     NaN         0       G       G       G
27   28      T     NaN         0       T       T       T
28   29      C     NaN         0       C       C       C
29   30      G     NaN         0       G       G       G
30   31      T       T  1.000000       C       C       T
31   32      C       C  1.000000       T       T       C

In [6313]:
merged_df.head(104)

     POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new
0      1      G     NaN         0       G       G       G
1      2      C     NaN         0       C       C       C
2      3      T     NaN         0       T       T       T
3      4      G     NaN         0       G       G       G
4      5      A     NaN         0       A       A       A
..   ...    ...     ...       ...     ...     ...     ...
99   100      C     NaN         0       C       C       C
100  101      C     NaN         0       C       C       C
101  102      T     NaN         0       T       T       T
102  103      G      GC  0.987559       G       G       G
103  104      C     NaN         0       C       0       C

[104 rows x 7 columns]

In [6314]:
merged_df.head(636)

     POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new
0      1      G     NaN         0       G       G       G
1      2      C     NaN         0       C       C       C
2      3      T     NaN         0       T       T       T
3      4      G     NaN         0       G       G       G
4      5      A     NaN         0       A       A       A
..   ...    ...     ...       ...     ...     ...     ...
631  631      G     NaN         0       G       G       G
632  632      G     NaN         0       G       G       G
633  633      G      GT  0.052245       G       G       G
634  634      T     NaN         0       T       T       T
635  635      G     NaN         0       G       G       G

[636 rows x 7 columns]

In [6315]:
filtered_df2 = merged_df[(merged_df['og_ref'] != merged_df['new_ref'])]

filtered_df2.shape #number of AF rows being changed

(110, 7)

In [6316]:
#using AF_old unless reference changed 
merged_df['AF_new'] = merged_df.apply(lambda x: 1 - float(x['AF_old']) if (x['og_ref'] != x['new_ref']) else float(x['AF_old']), axis=1) #note: 'AF_new' is all in float, 'AF_old' was in string and 0 was integer

merged_df

         POS og_ref REF_vcf AF_old ALT_old new_ref ALT_new  AF_new
0          1      G     NaN      0       G       G       G     0.0
1          2      C     NaN      0       C       C       C     0.0
2          3      T     NaN      0       T       T       T     0.0
3          4      G     NaN      0       G       G       G     0.0
4          5      A     NaN      0       A       A       A     0.0
...      ...    ...     ...    ...     ...     ...     ...     ...
13341  13310      T     NaN      0       T       T       T     0.0
13342  13311      C     NaN      0       C       C       C     0.0
13343  13312      G     NaN      0       G       G       G     0.0
13344  13313      C     NaN      0       C       C       C     0.0
13345  13314      G     NaN      0       G       G       G     0.0

[13346 rows x 8 columns]

In [6317]:
merged_df.iloc[30, :]

POS              31
og_ref            T
REF_vcf           T
AF_old     1.000000
ALT_old           C
new_ref           C
ALT_new           T
AF_new          0.0
Name: 30, dtype: object

In [6318]:
merged_df.head(82)

    POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new    AF_new
0     1      G     NaN         0       G       G       G  0.000000
1     2      C     NaN         0       C       C       C  0.000000
2     3      T     NaN         0       T       T       T  0.000000
3     4      G     NaN         0       G       G       G  0.000000
4     5      A     NaN         0       A       A       A  0.000000
..  ...    ...     ...       ...     ...     ...     ...       ...
77   78      T     NaN         0       T       T       T  0.000000
78   79      G     NaN         0       G       G       G  0.000000
79   80      A       A  0.977024      AC      AC       A  0.022976
80   81      C     NaN         0       C       C       C  0.000000
81   82      C     NaN         0       C       C       C  0.000000

[82 rows x 8 columns]

In [6319]:
#deal w deletions here

merged_df[merged_df['REF_vcf'].str.len() > 1]

         POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new    AF_new
102      103      G      GC  0.987559       G       G       G  0.987559
537      537      T      TG  0.957346       T       T       T  0.957346
633      633      G      GT  0.052245       G       G       G  0.052245
763      763      C     CGG  0.649318       C       C       C  0.649318
963      963      T  TGAGAC  0.008979       T       T       T  0.008979
...      ...    ...     ...       ...     ...     ...     ...       ...
11093  11069      G      GC  0.935852       G       G       G  0.935852
11142  11118      G      GC  0.863450       G       G       G  0.863450
11292  11268      C      CG  0.718024       C       C       C  0.718024
11442  11417      G    GGCA  0.205890       G       G       G  0.205890
13266  13235      G      GC  0.953411       G       G       G  0.953411

[63 rows x 8 columns]

In [6320]:
merged_df['AF_new'] = merged_df.apply(lambda x: 0 if (x['new_ref'] == x['ALT_new']) else x['AF_new'], axis=1)

merged_df.head(74)

    POS og_ref REF_vcf    AF_old ALT_old new_ref ALT_new    AF_new
0     1      G     NaN         0       G       G       G  0.000000
1     2      C     NaN         0       C       C       C  0.000000
2     3      T     NaN         0       T       T       T  0.000000
3     4      G     NaN         0       G       G       G  0.000000
4     5      A     NaN         0       A       A       A  0.000000
..  ...    ...     ...       ...     ...     ...     ...       ...
69   70      C     NaN         0       C       C       C  0.000000
70   71      C     NaN         0       C       C       C  0.000000
71   72      T     NaN         0       T       T       T  0.000000
72   73      C       C  0.996952       A       A       C  0.003048
73   74      A       A  0.999624       C       C       A  0.000376

[74 rows x 8 columns]

In [6321]:
# Ensure 'AF_old' is numeric
merged_df['AF_old'] = pd.to_numeric(merged_df['AF_old'], errors='raise')

# Filter rows where the length of 'REF_vcf' is greater than 1
copy_del_df = merged_df[merged_df['REF_vcf'].str.len() > 1].copy()

# Calculate additional columns
copy_del_df['add_len'] = copy_del_df['REF_vcf'].str.len() - 1
copy_del_df['inv_AF'] = 1 - copy_del_df['AF_old']

# Initialize a list to hold the new rows
rows = []

# Iterate through each row in the filtered DataFrame
for _, row in copy_del_df.iterrows():
    for i in range(1, row['add_len'] + 1):
        new_row = {
            'scenario': '>0.5' if row['AF_old'] > 0.5 else '<=0.5',
            'POS': row['POS'] + i,
            'add_len': row['add_len'],
            'AF': row['AF_old'],
            'inv_AF': row['inv_AF'],
            'del_POS': row['POS'] + i
        }
        rows.append(new_row)

# Create a new DataFrame from the list of new rows
new_df = pd.DataFrame(rows)

# Output the new DataFrame to check results
display(new_df.head())

  scenario  POS  add_len        AF    inv_AF  del_POS
0     >0.5  104        1  0.987559  0.012441      104
1     >0.5  538        1  0.957346  0.042654      538
2    <=0.5  634        1  0.052245  0.947755      634
3     >0.5  764        2  0.649318  0.350682      764
4     >0.5  765        2  0.649318  0.350682      765

In [6322]:
# Merge the two DataFrames on 'POS'
merged_updated_df = pd.merge(merged_df, new_df[['scenario', 'POS', 'AF', 'inv_AF']], on='POS', how='left')


merged_updated_df.head(766)

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
0,1,G,NaN,0.000000,G,G,G,0.0,NaN,NaN,NaN
1,2,C,NaN,0.000000,C,C,C,0.0,NaN,NaN,NaN
2,3,T,NaN,0.000000,T,T,T,0.0,NaN,NaN,NaN
3,4,G,NaN,0.000000,G,G,G,0.0,NaN,NaN,NaN
4,5,A,NaN,0.000000,A,A,A,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
761,761,C,NaN,0.000000,C,C,C,0.0,NaN,NaN,NaN
762,762,T,NaN,0.000000,T,T,T,0.0,NaN,NaN,NaN
763,763,C,CGG,0.649318,C,C,C,0.0,NaN,NaN,NaN
764,764,G,NaN,0.000000,G,G,G,0.0,>0.5,0.649318,0.350682
765,765,G,NaN,0.000000,G,G,G,0.0,>0.5,0.649318,0.350682

In [6323]:
# merged_updated_df.loc[merged_updated_df['new_ref'] == '0', 'AF_new'].shape

In [6324]:
merged_updated_df[merged_updated_df['new_ref'] == '0']

/Users/fionachow/opt/anaconda3/envs/rl/lib/python3.9/site-packages/IPython/core/displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
103,104,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.987559,0.012441
538,538,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.957346,0.042654
1674,1672,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.031593,0.968407
1675,1672,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1676,1673,T,TCCCA,0.318475,T,0,T,0.681525,>0.5,0.596132,0.403868
1677,1674,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1678,1674,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.318475,0.681525
1679,1675,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1680,1675,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.318475,0.681525
1681,1676,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1682,1676,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.318475,0.681525
1763,1757,T,NaN,0.000000,T,0,T,1.000000,>0.5,0.947604,0.052396
3160,3153,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.949975,0.050025
3419,3412,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.728925,0.271075
5306,5294,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.957393,0.042607
5316,5304,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.950704,0.049296
5976,5892,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.602768,0.397232
5977,5892,G,NaN,0.000000,G,0,G,1.000000,<=0.5,0.156723,0.843277
6621,6535,G,GGGC,0.011033,G,0,G,0.988967,>0.5,0.596474,0.403526
6622,6535,G,GGGC,0.011033,G,0,G,0.988967,<=0.5,0.090127,0.909873
6623,6536,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.596474,0.403526
6624,6536,G,NaN,0.000000,G,0,G,1.000000,<=0.5,0.090127,0.909873
6625,6536,G,NaN,0.000000,G,0,G,1.000000,<=0.5,0.011033,0.988967
6626,6537,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.596474,0.403526
6627,6537,G,NaN,0.000000,G,0,G,1.000000,<=0.5,0.090127,0.909873
6628,6537,G,NaN,0.000000,G,0,G,1.000000,<=0.5,0.011033,0.988967
6629,6538,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596474,0.403526
6630,6538,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.090127,0.909873
6631,6538,C,NaN,0.000000,C,0,C,1.000000,<=0.5,0.011033,0.988967
7418,7322,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.922841,0.077159
7459,7363,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.938994,0.061006
7466,7370,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.836368,0.163632
11189,11070,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.935852,0.064148
11238,11119,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.863450,0.136550
11388,11269,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.718024,0.281976
13362,13236,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.953411,0.046589

In [6325]:
merged_updated_df[merged_updated_df['scenario'] == '>0.5']

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
103,104,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.987559,0.012441
538,538,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.957346,0.042654
764,764,G,NaN,0.000000,G,G,G,0.000000,>0.5,0.649318,0.350682
765,765,G,NaN,0.000000,G,G,G,0.000000,>0.5,0.649318,0.350682
1675,1672,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1676,1673,T,TCCCA,0.318475,T,0,T,0.681525,>0.5,0.596132,0.403868
1677,1674,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1679,1675,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1681,1676,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596132,0.403868
1763,1757,T,NaN,0.000000,T,0,T,1.000000,>0.5,0.947604,0.052396
2493,2487,G,NaN,0.000000,G,G,G,0.000000,>0.5,0.542124,0.457876
2494,2488,C,NaN,0.000000,C,C,C,0.000000,>0.5,0.542124,0.457876
2495,2489,G,G,0.006243,GACC,G,GACC,0.006243,>0.5,0.542124,0.457876
2496,2489,G,G,0.019603,GACT,G,GACT,0.019603,>0.5,0.542124,0.457876
3160,3153,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.949975,0.050025
3419,3412,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.728925,0.271075
5306,5294,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.957393,0.042607
5316,5304,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.950704,0.049296
5976,5892,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.602768,0.397232
6621,6535,G,GGGC,0.011033,G,0,G,0.988967,>0.5,0.596474,0.403526
6623,6536,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.596474,0.403526
6626,6537,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.596474,0.403526
6629,6538,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.596474,0.403526
7418,7322,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.922841,0.077159
7459,7363,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.938994,0.061006
7466,7370,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.836368,0.163632
11189,11070,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.935852,0.064148
11238,11119,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.863450,0.136550
11388,11269,G,NaN,0.000000,G,0,G,1.000000,>0.5,0.718024,0.281976
13362,13236,C,NaN,0.000000,C,0,C,1.000000,>0.5,0.953411,0.046589

In [6326]:
merged_updated_df[merged_updated_df['scenario'] == '<=0.5'].head()

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
634,634,T,NaN,0.0,T,T,T,0.0,<=0.5,0.052245,0.947755
964,964,G,NaN,0.0,G,G,G,0.0,<=0.5,0.008979,0.991021
965,965,A,NaN,0.0,A,A,A,0.0,<=0.5,0.008979,0.991021
966,966,G,NaN,0.0,G,G,G,0.0,<=0.5,0.008979,0.991021
967,967,A,NaN,0.0,A,A,A,0.0,<=0.5,0.008979,0.991021

In [6327]:
# Update 'AF_new' based on condition
merged_updated_df.loc[merged_updated_df['new_ref'] == '0', 'AF_new'] = merged_updated_df['inv_AF']

merged_updated_df.head(104)

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
0,1,G,NaN,0.000000,G,G,G,0.000000,NaN,NaN,NaN
1,2,C,NaN,0.000000,C,C,C,0.000000,NaN,NaN,NaN
2,3,T,NaN,0.000000,T,T,T,0.000000,NaN,NaN,NaN
3,4,G,NaN,0.000000,G,G,G,0.000000,NaN,NaN,NaN
4,5,A,NaN,0.000000,A,A,A,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
99,100,C,NaN,0.000000,C,C,C,0.000000,NaN,NaN,NaN
100,101,C,NaN,0.000000,C,C,C,0.000000,NaN,NaN,NaN
101,102,T,NaN,0.000000,T,T,T,0.000000,NaN,NaN,NaN
102,103,G,GC,0.987559,G,G,G,0.000000,NaN,NaN,NaN
103,104,C,NaN,0.000000,C,0,C,0.012441,>0.5,0.987559,0.012441

In [6328]:
merged_updated_df['ALT_new'] = merged_updated_df.apply(lambda x: '0' if pd.notna(x['inv_AF']) and x['new_ref']!='0'  else x['og_ref'], axis=1)
merged_updated_df['AF_new'] = merged_updated_df.apply(lambda x: x['AF'] if pd.notna(x['inv_AF']) and x['ALT_new']=='0' else x['AF_new'], axis=1)
merged_updated_df.head(766)

,POS,og_ref,REF_vcf,AF_old,ALT_old,new_ref,ALT_new,AF_new,scenario,AF,inv_AF
0,1,G,NaN,0.000000,G,G,G,0.000000,NaN,NaN,NaN
1,2,C,NaN,0.000000,C,C,C,0.000000,NaN,NaN,NaN
2,3,T,NaN,0.000000,T,T,T,0.000000,NaN,NaN,NaN
3,4,G,NaN,0.000000,G,G,G,0.000000,NaN,NaN,NaN
4,5,A,NaN,0.000000,A,A,A,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
761,761,C,NaN,0.000000,C,C,C,0.000000,NaN,NaN,NaN
762,762,T,NaN,0.000000,T,T,T,0.000000,NaN,NaN,NaN
763,763,C,CGG,0.649318,C,C,C,0.000000,NaN,NaN,NaN
764,764,G,NaN,0.000000,G,G,0,0.649318,>0.5,0.649318,0.350682
765,765,G,NaN,0.000000,G,G,0,0.649318,>0.5,0.649318,0.350682

In [6329]:
merged_updated_df.drop(columns=['scenario','AF', 'inv_AF','REF_vcf', 'og_ref', 'AF_old', 'ALT_old'], inplace=True)

display(merged_updated_df.head())

   POS new_ref ALT_new  AF_new
0    1       G       G     0.0
1    2       C       C     0.0
2    3       T       T     0.0
3    4       G       G     0.0
4    5       A       A     0.0

In [6330]:
merge_updated_df = merged_updated_df[merged_updated_df['AF_new']!=0] #new vcf output

In [6331]:
merge_updated_df.shape

(569, 4)

In [6332]:
merge_updated_df[merge_updated_df['AF_new']>0.5].shape

(33, 4)

In [6333]:
merge_updated_df[merge_updated_df['AF_new']>0.5]

         POS new_ref ALT_new    AF_new
385      386   TGGCC       T  0.899331
764      764       G       0  0.649318
765      765       G       0  0.649318
1674    1672       0       C  0.968407
1678    1674       0       C  0.681525
1680    1675       0       C  0.681525
1682    1676       0       C  0.681525
1755    1749       C       C  0.570535
2493    2487       G       0  0.542124
2494    2488       C       0  0.542124
2495    2489       G       0  0.542124
2496    2489       G       0  0.542124
5977    5892       0       G  0.843277
6622    6535       0       G  0.909873
6624    6536       0       G  0.909873
6625    6536       0       G  0.988967
6627    6537       0       G  0.909873
6628    6537       0       G  0.988967
6630    6538       0       C  0.909873
6631    6538       0       C  0.988967
7896    7799       T       C  0.518638
8786    8688   CCCGT       C  0.982039
8787    8688   CCCGT       C  0.990615
8788    8688   CCCGT       C  0.990453
11001  10882       C       G  1.000000
11078  10959       A       A  0.564246
11196  11077      GC       G  0.660524
11205  11086     GCC       G  0.514975
12167  12047       G       C  0.955280
12168  12047       G       C  0.971276
12169  12047       G       C  0.950464
12846  12722    CGCG       C  0.955263
13205  13079       T       T  0.508117